apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servicecomposer.fullname" . }}-secret
  labels:
    {{- include "servicecomposer.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ .Values.config.appSecretKey | b64enc | quote }}
