apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-secret
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
