apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-secret
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
