apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connectivitymanager.fullname" . }}-config
  labels:
    {{- include "connectivitymanager.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: {{ .Values.config.debug | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DB_ENGINE: {{ .Values.config.dbEngine | quote }}
  DB_HOST: {{ include "connectivitymanager.postgresql.fullname" . }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  REDIS_HOST: {{ include "connectivitymanager.redis.fullname" . }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REDIS_AUTH_USERNAME: {{ include "connectivitymanager.redis.username" . }}
  REDIS_ENABLE_TLS: {{ .Values.config.redisTlsEnabled | quote }}
  VIOS_SBR_HOST: {{ .Values.config.sbrHost | quote }}
  VIOS_SBR_PORT: {{ .Values.config.sbrPort | quote }}
  VIOS_SMA_HOST: {{ .Values.config.smaHost | quote }}
  VIOS_SMA_PORT: {{ .Values.config.smaPort | quote }}
  SYSTEM_ENV: {{ .Values.config.systemEnv | quote }}
