apiVersion: v1
kind: Secret
metadata:
  name: {{ include "repository.fullname" . }}-secret
  labels:
    {{- include "repository.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_AUTH_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ .Values.config.appSecretKey | b64enc | quote }}
