postgresql:
  enabled: true
  auth:
    username: viosuser
    password: viospassword
    database: connectivitymanager

config:
  replicaCount: 1
  appPort: 8000
  type: NodePort
  nodePort: 30101
  dbPort: 5432
  debug: "True"
  logLevel: DEBUG
  smaHost: servicemanager
  smaPort: 8000
  agaHost: apigateway
  agaPort: 8000
  vyosServer: 10.68.113.147
  vyosKey: demo_key
  vyosEthernetPort: eth0
  tunnelSubnet: 172.16.253.0/24
  netOs: disable

image:
  repository: digicatapult/vios-connectivitymanager
  pullPolicy: Always
  tag: 0.1.1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false
  annotations: {}
  name: ""
