apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgeproxy.fullname" . }}
  labels:
    {{- include "edgeproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      {{- include "edgeproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "edgeproxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "edgeproxy.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "edgeproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.appPort }}
          envFrom:
          - configMapRef:
              name: {{ include "edgeproxy.fullname" . }}-config
          - secretRef:
              name: {{ include "edgeproxy.fullname" . }}-secret
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
