apiVersion: v1
kind: Service
metadata:
  name: {{ include "edgeproxy.fullname" . }}
  labels:
    {{- include "edgeproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.type }}
  ports:
    - port: {{ .Values.config.appPort }}
      targetPort: api-port
      protocol: TCP
      name: http
  selector:
    {{- include "edgeproxy.selectorLabels" . | nindent 4 }}
