apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-secret
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  DB_USERNAME: {{ .Values.mongodb.auth.username | b64enc | quote }}